config/routes.rb
Findtuned::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'static_pages#home'
  
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/blog', to: 'static_pages#blog'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
    format:     { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  
  private 
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  # Force signout to prevent CSRF attacks
  def handle_unverified_request
    sign_out
    super
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end
  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def about
  end
  
  def contact
  end

  def blog
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the FindTuned!"
      redirect_to @user
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "FindTuned: Find your new jam band"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end
  def signed_in?
    !current_user.nil?
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
<div class='footer-inner'>
  <div class='container'>
    <small>
      CREATED BY MUSCIANS MATCH @ UCLA <br>
      COPYRIGHT 2013
    </small>
  </div>
</div>
</footer>

app/views/layouts/_header.html.erb
<div class="head-nav"> <div class="container">
    <div class="pull-left">
      <%= link_to image_tag("logo.png", :alt => "logo"), '/' %>
    </div>
    <nav>
    <ul class="nav nav-pills pull-right">
      <li><%= link_to "ABOUT US", about_path %></li>
      <li><%= link_to "CONTACT",  contact_path %></li>
      <li><%= link_to "BLOG", blog_path %></li>
      <li class="dropdown">
      <li id="fat-menu" class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        COMING SOON 
        <!--<b class="caret"></b> -->
      </a>
      <!--
      <ul class="dropdown-menu">
        <% if signed_in? %>
          <li><%= link_to "USERS", '#' %></li>
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Settings", '#' %></li>
          <li class="divider"></li>
          <li>
          <%= link_to "Sign out", signout_path, method: "delete" %>
          </li>
        <% else %>
          <li><%= link_to "Sign in", signin_path %></li>
        <% end %>
      </ul>
      </li>
      <ul class="dropdown-menu">
        </li>
      </ul>
      -->
      </li>
    </ul>
    </nav>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <link href='http://fonts.googleapis.com/css?family=Roboto:100,300' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class='container main'>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About Us </h1>

app/views/static_pages/blog.html.erb
<% provide(:title, "Blog") %>
<h1>Blog</h1>

app/views/static_pages/contact.html.erb
<%provide(:title, 'Contact') %>
<h1>Contact Us</h1>

app/views/static_pages/home.html.erb
<div class='row'>
  <div class='span5'>
    <p class='question'>What is <strong>FindTuned</strong>?</p>
    <p class='image'>
      <%= image_tag("image_home.png", :alt => "image_home")%>
      </p>  
    </div>
  <div class='span7'>
    <p class='answer'>
    FindTuned is a website where you can find local musicians to jam with!
    Members can build custom sharable musician profiles, containing links
    to all of your music and videos!
    </p>

    <p class='image'>
    <%= image_tag("logo_big.png", :alt => "logo_big") %>
    Coming Soon!
    </p>

    <div class='row'>
      <div class='span3'>
        <p>
        <strong>I am a...</strong>
        </p>
      </div>
      <div class='span3'>
        <p> 
        <strong class='sea'>
          looking for...
        </strong>
        </p>
      </div>
      <div class='span1'>
        <p> 
        <strong>near...</strong>
        </p>
      </div>
    </div>

    <form class="form-search">
      <input class="span3 " type="text" placeholder="guitarist">
      <input class="span3 search red" type="text" placeholder="vocalist">
      <input class="span1 search" type="text" placeholder="90024">
      <div class='submit-btn' >
          <!-- <button class="btn btn-large" type="submit">FIND NOW</button> -->
          <a class="btn btn-large btn-sea" href="#">FIND NOW</a>
        </div>
    </form>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div>
  <div class ="row-fluid">
    <div class ="span12">
      <div class = "row-fluid">
        <div class = "span7">
          <p class = "title">
          BUILD YOUR FINDTUNED PROFILE
          </P>
        </div>
        <div class = "span5 pull-right">
          <P class = "sub-title">
          It is important to provide all your information to ensure you get the best results and experience from FindTuned!
          </P>
        </div>
      </div>

      <hr>

      <div class = "row-fluid pull-right">
        <div class = "span2">
          <p class = "sub-section">Name</p>
          <input type="text" placeholder="first name">
          <input type="text" placeholder="last name">
        </div>

        <div class = "span3">
          <p class = "sub-section">Email+Passward</p>
          <input type="text" placeholder="example@ucla.edu">
          <input type="text" placeholder="******">
        </div>

        <div class = "span1">
          <p class = "sub-section">Gender</p>
          <label class="radio">
            <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked>M</label>
          <label class="radio">
            <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">F</label>
        </div>

        <div class = "span2">
          <p class = "sub-section">Date of Birth</p>
          <form class="input form-inline">
            <input type="text" class="input-smini" placeholder="08">
            <input type="text" class="input-smini" placeholder="15">
            <input type="text" class="input-mmini" placeholder="1992">
          </form>
        </div>

        <div class = "span4 row-fluid">
          <p class = "sub-section">I am a...</p>
          <div class = "span3">
            <p class = "subsection">
            <label class="radio">
              <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked>Musician</label>
            <label class="radio">
              <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">Non-Musician</label>
          </div>
          <div class = "span8">
            <p class = "sub-section-italic">This will determine your profile type and the rest of the content to fill out
            </p>
          </div>
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class ="row-fluid">
    <div class ="span12">
      <div class = "row-fluid">
        <div class = "span7">
          <p class = "title">
          MUSICIAN PROFILE
          </P>
        </div>
      </div>


      <div class = "row-fluid">

        <div class = "span3">
          <p class = "sub-section">What do you play?</p>
          <textarea rows="3" placeholder = "guitar, keybord, vocals"></textarea>
          <p class = "sub-section-italic">Seperate different terms with commas -- this will add tags to your profile, which will help others to find you!
          </p>
        </div>

        <div class = "span3">

          <div class = "span12  sub-section">Looking for BandMates?
            <label class="radio">
              <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked>Yes!</label>
            <div class = "span9">
              <p class = "sub-section-small">Who? Add tags.</p>
              <textarea rows="3" placeholder = "drummer, pianist, triangle"></textarea> </div>
          </div>

          <div class = "span12">
            <label class="radio">
              <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2" checked>No, just want to browse.</label>
            <p class = "sub-section-italic">Don't worry! You can change your mind later.</p>
          </div>
        </div>

        <div class = "span4">
          <p class = "sub-section">A quick word about you.</p>
          </p>
          <textarea class ="sub-section-italic" rows="5" placeholder = "Please write a short intro about yourself! Your hobbies, where you grew up, your dreams, goals, favorite artists - anything! This will show up on your profile, and you can always come back and edit is later on."></textarea>
          <p class = "sub-section">Your music
          <p class = "sub-section-italic"> + Links to your YouTube or SoundCloud!
          </p>
          <input type="text" placeholder="http://youtube/4QHTpeNhO3U">
          <input type="text" placeholder="http://snd.sc/ZfKQqu">
          </p>
        </div>


        <div class = "span2">
          <p class = "sub-section">Photo</p>
          <button class="btn btn-mini btn-sea" type="button">UPLOAD</button>
          <%= image_tag("preview.png", :alt => "image_home")%>
          <p class = "sub-section-italic">[preview]</p>
          <div class='submit-btn' >
            <a class="btn btn-large btn-sea" href="#">SUBMIT!</a>
          </div>


        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h1>